learning_system/classroom/urls.py
from django.urls import path
from classroom import views
from django.contrib import admin
app_name = 'classroom'

urlpatterns =[
    path('admin/', admin.site.urls),
    path('signup/',views.SignUp,name="signup"),
    path('signup/student_signup/',views.StudentSignUp,name="StudentSignUp"),
    path('signup/teacher_signup/',views.TeacherSignUp,name="TeacherSignUp"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('student/<int:pk>/',views.StudentDetailView.as_view(),name="student_detail"),
    path('teacher/<int:pk>/',views.TeacherDetailView.as_view(),name="teacher_detail"),
    path('update/student/<int:pk>/',views.StudentUpdateView,name="student_update"),
    path('update/teacher/<int:pk>/',views.TeacherUpdateView,name="teacher_update"),
    path('student/<int:pk>/enter_marks',views.add_marks,name="enter_marks"),
    path('student/<int:pk>/marks_list',views.student_marks_list,name="student_marks_list"),
    path('marks/<int:pk>/update',views.update_marks,name="update_marks"),
    path('student/<int:pk>/add',views.add_student.as_view(),name="add_student"),
    path('student_added/',views.student_added,name="student_added"),
    path('students_list/',views.students_list,name="students_list"),
    path('teachers_list/',views.teachers_list,name="teachers_list"),
    path('teacher/class_students_list',views.class_students_list,name="class_student_list"),
    path('student/<int:pk>/all_marks',views.StudentAllMarksList.as_view(),name="all_marks_list"),
    path('student/<int:pk>/message',views.write_message,name="write_message"),
    path('teacher/<int:pk>/messages_list',views.messages_list,name="messages_list"),
    path('teacher/write_notice',views.add_notice,name="write_notice"),
    path('student/<int:pk>/class_notice',views.class_notice,name="class_notice"),
    path('upload_assignment/',views.upload_assignment,name="upload_assignment"),
    path('class_assignment/',views.class_assignment,name="class_assignment"),
    path('assignment_list/',views.assignment_list,name="assignment_list"),
    path('update_assignment/<int:id>/',views.update_assignment,name="update_assignment"),
    path('assignment_delete/<int:id>/',views.assignment_delete,name="assignment_delete"),
    path('submit_assignment/<int:id>/',views.submit_assignment,name="submit_assignment"),
    path('submit_list/',views.submit_list,name="submit_list"),
    path('change_password/',views.change_password,name="change_password"),
]

learning_system/learning_system/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('classroom/',include('classroom.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/class_assignment.html
{% extends 'classroom/base.html' %}
{% block content %}

<div class="container">
  <div class="jumbotron">

{% if student.student_assignment.count == 0 %}
  <h2>No assignments Yet</h2>
{% else %}
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Assignment Name</th>
        <th scope="col">Uploaded By</th>
        <th scope="col">Uploaded Date</th>
        <th scope="col">Deadline</th>
        <th scope="col">Download</th>
        <th scope="col">Subission Status</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for assignment in student.student_assignment.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ assignment.assignment_name }}</td>
          <td>{{ assignment.teacher }}</td>
          <td>{{ assignment.created_at }}</td>
          <td>{{ assignment.deadline }}</td>
          <td><a href="{{ assignment.assignment.url }}" class="btn btn-primary" target="_blank">Download</a></td>
          {% if assignment in assignment_list %}
            <td>Submitted</td>
            {% else %}
            <td><a href="{% url 'classroom:submit_assignment' id=assignment.id %}" class="btn btn-primary">Submit</a></td>
            {% now "Y-m-d" as todays_date %}
            {% if todays_date > deadline|date:"Y-m-d" %}
               <td>Delayed</td>
            {% endif %}
            {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}
</div>
</div>
{% endblock %}

templates/class_notice_list.html
{% extends 'classroom/base.html' %}
{% load static %}
{% block content %}

<div class="container">

  {% if student.class_notice.count == 0 %}
  <h2>No Notice Yet.</h2>
  {% else %}

  {% for notice in student.class_notice.all %}
  <div class="notice">
  <div class="row">
    <div class="col-md-1">
      {% if notice.teacher.teacher_profile_pic %}
      <img src="{{ notice.teacher.teacher_profile_pic.url }}" class="notice-img">
      {% else %}
      <img src="{% static 'images/login-avatar.PNG' %}" class="notice-img">
      {% endif %}
    </div>
    <div class="col-md-11">
      <div class="notice-details">
        <div class="row">
        <div class="col-md-3">
          <h5>By: {{ notice.teacher.name }}</h5>
        </div>
        <div class="col-md-3">
          <h5>Subject: {{ notice.teacher.subject_name }}</h5>
        </div>
        <div class="col-md-3">
          <h5>{{ notice.created_at }}</h5>
        </div>
        </div>
        <hr>
        <h2>{{ notice.message_html|safe }}</h2>
        </div>
    </div>
  </div>
  </div>
  {% endfor %}
  {% endif %}
</div>



<!--
{% if student.class_notice.count == 0 %}
<h2>No notice yet</h2>
{% else %}
{% for notice in student.class_notice.all %}
<div class="">
  <h3>{{ notice.message_html|safe }}</h3>
  <div class="row">
    <div class="col-md-6">
      <p>By: {{ notice.teacher.name }}</p>
    </div>
    <div class="col-md-6">
      <p>Date: {{ notice.created_at }}</p>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}

-->

{% endblock %}

templates/class_students_list.html
{% extends "classroom/base.html" %}
{% load static %}
{% block content %}

<div class="student-list">
<div class="container">
  {% if class_students_list.count == 0 %}
    <h1>No students in the class.</h1>
    {% else %}

  <form method='GET' action="{% url 'classroom:class_student_list' %}">
    <p>Search Student: <input type='search' name='q' placeholder='Search'></p>
  </form>
  <div class="row">
  {% for student in class_students_list %}
  <div class="col-6 col-md-4">
  <div class="student-box">
    <div class="imgBx">
      {% if student.student_profile_pic %}
      <img src="{{ student.student_profile_pic.url }}" alt="">
      {% else %}
      {% if forloop.counter0|divisibleby:"2" %}
      <img src="{% static 'images/login-avatar.PNG' %}" alt="">
      {% else %}
      <img src="{% static 'images/login-avatar-2.PNG' %}" alt="">
      {% endif %}
      {% endif %}
    </div>
    <div class="content">
      <h3>{{ student.name }}</h3>
      <p><i class="far fa-user"></i> Username: {{ student.user.username }}</p>
      <p><i class="fal fa-user-tag"></i> Roll No.: {{ student.roll_no }}</p>
      <p><i class="far fa-phone"></i> Phone: {{ student.phone }}</p>
      <p><i class="far fa-envelope-open-text"></i> Email ID: {{ student.email }}</p>
      <a href="{% url 'classroom:student_marks_list' pk=student.pk %}"><p class="add-button">View Marks Profile</p></a>
    </div>
  </div>
  </div>
  {% endfor %}
  </div>
</div>
{% endif %}
</div>


<!--
<div class="jumbotron">
  {% if teacher.class_students.count == 0 %}
    <h1>No students in the class.</h1>
    {% else %}
    <h1>Your class students list.</h1>
    <br>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Roll No.</th>
          <th scope="col">Name</th>
          <th scope="col">Email Id</th>
          <th scope="col"> </th>
        </tr>
      </thead>
      <tbody>
        {% for student in teacher.class_students.all %}
        <tr>
          <th>{{ student.roll_no }}</th>
          <th>{{ student.name }}</th>
          <th>{{ student.email }}</th>
          <th> <a class="btn btn-primary" href="{% url 'classroom:student_marks_list' pk=student.pk %}">View Marks Profile</a> </th>
        </tr>

        {% endfor %}
      </tbody>
    </table>
    <p><a class="btn btn-danger" href="{% url 'classroom:write_notice' %}">Add Notice</a></p>
  {% endif %}

</div>
-->
{% endblock %}

templates/index.html
{% extends 'classroom/base.html' %}
{% load static %}
{% block content %}

{% if messages %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  {% for message in messages %}
    <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
  {% endfor %}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

<div class="banner" style="background-color:rgb(121, 180, 222) ;" >
      <img src="{% static 'images\profile-background-3.PNG' %}" alt="">
      <div class="content">
        <h1>Poductive learning</h1>
        <p>A Student-Teacher Portal</p>
      </div>
    </div>

    <div class="use-content" style="background-color:rgb(80, 151, 210)">
      <h1>Our Services</h1>
      <div class="row">
        <div class="col-12 col-md-6">
          <div class="box">
            <div class="imgBx">
              <img src="{% static 'images/homeimg-1.PNG' %}" alt="">
            </div>
            <div class="content">
              <h3>For Teacher</h3>
              <ol>
                <li>Teachers can add student in their class through Add Student option.</li>
                <li>After adding students in their class, Teacher can give or edit their class students marks.</li>
                <li>Teachers can also write notice which will be send to all students in their class.</li>
                <li>Teachers can upload assignments through upload assignment options.</li>
                <li>Teacher can check their student's assignment submission and give them marks accordingly.</li>
                <li>Students can message Teachers directly and their messages can be seen in Inbox.</li>
                <li>Teacher can also all the marks given by them to a student by accessing their Marks profile and can edit their marks.</li>
                <li>User can add profile pic through edit profile option.</li>
              </ol>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6" >
          <div class="box">
            <div class="imgBx">
              <img src="{% static 'images/teacher-1.PNG' %}" alt="">
            </div>
            <div class="content">
              <h3>For Student</h3>
              <ol>
                <li>Students can login in the portal and keep themselves updated of all the activities going on in the class.</li>
                <li>Students can see the notice given by their teacher in the Class Notice option.</li>
                <li>Students can download their assignments in the Assignments option and can also submit it their. ( Once assignment is submitted, it can't be changed later. )</li>
                <li> Students can contact any teacher through message option in All Teachers List. </li>
                <li>Students can check their marks in the Marks option.</li>
                <li>User can add profile pic through edit profile option.</li>
              </ol>
          </div>
        </div>
      </div>
    </div>
    </div>

    <div class="research" >
      <div class="row" style="background-color:rgb(0, 90, 139)">
        <div class="col-md-4">
          <img src="{% static 'images/mastery-based-education.PNG' %}" alt="">
        </div>
        <div class="col-md-8" >
          <div class="digital-content" >
            <p>If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.</p>
          </div>
        </div>
      </div>
    </div>

    <div class="social" style="background-color: rgb(6, 24, 78);">
      <h3>Contact details </h3>
      <a class="social-icon" href="#"><i class="fab fa-facebook-f"></i></a>
      <a class="social-icon" href="#"><i class="fab fa-twitter"></i></a>
      <a class="social-icon" href="#"><i class="fab fa-instagram"></i></a>
      <a class="social-icon" href="#"><i class="fab fa-google"></i></a>
      <a class="social-icon" href="#"><i class="fab fa-linkedin-in"></i></a>
    </div>
 
{% endblock %}

templates/signup.html
{% extends 'classroom/base.html' %}
{% load static %}
{% block content %}

  <div class="login-page">
  <img src="{% static 'images/student-signup.PNG' %}" alt="">
    <div class="signup">
      <h1>Sign Up</h1>
      <br>
      <a href="{% url 'classroom:StudentSignUp' %}"><p>I'm a Student</p> </a>
      <br>
      <a href="{% url 'classroom:TeacherSignUp' %}"><p>I'm a Teacher</p> </a>
    </div>
    </div>



{% endblock %}

templates/student_added.html
{% extends 'classroom/base.html' %}
{% block content %}

<h1>Student added successfully in classroom.</h1>
<h3>Go to All Students List to add more students.</h3>

{% endblock %}

templates/student_detail_page.html
{% extends 'classroom/base.html' %}
{% load static %}
{% block content %}

<div class="profile">
  <img src="{% static 'images/profile-background-3.PNG' %}" alt="">
  <div class="profile-box">
    {% if student.student_profile_pic %}
      <img src="{{ student.student_profile_pic.url }}">
    {% else %}
      <img src="{% static 'images/login-avatar.PNG' %}" alt="">
    {% endif %}
    <div class="profile-details">
      <h1>{{ student.name }}</h1>
      <br>
      <p><i class="far fa-user"></i> Username: {{ student.user.username }}</p>
      <p><i class="fal fa-user-tag"></i> Roll No.: {{ student.roll_no }}</p>
      <p><i class="far fa-phone"></i> Phone: {{ student.phone }}</p>
      <p><i class="far fa-envelope-open-text"></i> Email ID: {{ student.email }}</p>
      <a href="{% url 'classroom:student_update' pk=user.pk %}"> <p class="edit-button">Edit Profile</p> </a>
    </div>
  </div>
</div>

<!--
<div class="row">
  <div class="col-md-3">
    {% if student.student_profile_pic %}
      <img src="{{ student.student_profile_pic.url }}">
    {% else %}
      <img src="" alt="">
    {% endif %}
  </div>
  <div class="col-md-9">
    <h1>{{ student.user.username }}</h1>
    <br>
    <p>Name: {{ student.name }}</p>
    <p>Roll No.: {{ student.roll_no }}</p>
    <p>Email Id: {{ student.email }}</p>
    <p>Phone: {{ student.phone }}</p>
    <br>
    <p> <a class="btn btn-primary" href="{% url 'classroom:student_update' pk=user.pk %}">Edit profile</a> </p>
  </div>
</div>
-->

{% endblock %}

templates/student_marks_list.html
{% extends 'classroom/base.html' %}
{% block content %}

<div class="container">
  <div class="jumbotron">
{% if given_marks.count == 0 %}
<h2>You have not given any marks to {{ student.name }}.</h2>
{% else %}
<h3>Marks profile of {{ student.name }}</h3>

<table class='table'>
  <thead class="thead-dark">
    <tr>
      <th scope="col">Sr. no.</th>
      <th scope="col">Topic</th>
      <th scope="col">Marks Obtained</th>
      <th scope="col">Max. Marks</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for marks in given_marks %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <th>{{ marks.subject_name }}</th>
      <th>{{ marks.marks_obtained }}</th>
      <th>{{ marks.maximum_marks }}</th>
      <th> <a class="btn btn-primary" href="{% url 'classroom:update_marks' pk=marks.pk %}">Update</a> </th>
    </tr>
    {% endfor %}
  </tbody>
</table>
<br>

{% endif %}
<p> <a class="btn btn-danger" href="{% url 'classroom:enter_marks' pk=student.pk %}">Add marks</a> </p>

</div>
</div>

{% endblock %}

templates/student_signup.html
{% extends 'classroom/base.html' %}
{% load static %}
{% block content %}

<div class="login-page">
    <img src="{% static 'images/login-background.PNG' %}" alt="">
    <div class="student-signup-form">
      {% if registered %}
      <h1>Thank you for registering.</h1>
      {% else %}
      <h1>Sign up as a Student.</h1>
      <h3>Fill out the form:</h3>

      <form method="post">
        {% csrf_token %}

        {{ student_profile_form.non_field_errors }}

        <p> <label>{{ student_profile_form.name.label_tag }}</label>{{ student_profile_form.name }}</p>
        <p> <label >{{ student_profile_form.roll_no.label_tag }}</label>  {{ student_profile_form.roll_no }}</p>
        <p> <label for="">{{ student_profile_form.phone.label_tag }}</label> {{ student_profile_form.phone }}</p>
        <p> <label for="">{{ student_profile_form.email.label_tag }}</label>{{ student_profile_form.email }}</p>

        {{ user_form.non_field_errors }}

        <p> <label for="">{{ user_form.username.label_tag }}</label>{{ user_form.username }}</p>
        <p> {{ user_form.username.help_text }}</p>
        <p> <label for="">{{ user_form.password1.label_tag }}</label>{{ user_form.password1 }}</p>
        <p>Password can't be similar to your other fields and must contain atleast 8 characters.</p>
        <p> <label for="">{{ user_form.password2.label_tag }}</label>{{ user_form.password2 }}</p>
        <p> {{ user_form.password2.help_text }} </p>
        <input type="submit" name="" value="Sign Up">
      </form>
      <a href="{% url 'classroom:login' %}">Already have an account.</a>
      {% endif %}
    </div>
</div>

{% endblock %}

templates/student_update_page.html
{% extends "classroom/base.html" %}
{% load bootstrap4 %}
{% block content %}

<div class="container">
<div class="jumbotron">
  {% if profile_updated %}
  <h1>Your profile is updated successfully.</h1>
  {% else %}
  <h1>Update Profile</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit" name="" value="Submit">
  </form>
  {% endif %}
</div>
</div>

{% endblock %}

templates/submit_assignment.html
{% extends 'classroom/base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
<div class="jumbotron">
  <h1>Submit Assignment</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" name="" value="Submit">

  </form>
</div>
</div>
{% endblock %}

templates/teacher_update_page.html
{% extends "classroom/base.html" %}
{% load bootstrap4 %}
{% block content %}


<div class="container">
  <div class="jumbotron">
{% if profile_updated %}
<h1>Your profile has been successfully updated.</h1>
{% else %}
  <h1>Update Profile</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-primary" type="submit" name="" value="Submit">
  </form>
  </div>
  </div>

{% endif %}

{% endblock %}

templates/teachers_list.html
{% extends "classroom/base.html" %}
{% load static %}
{% block content %}

<div class="student-list">
<div class="container">
  <form method='GET' action="{% url 'classroom:teachers_list' %}">
    <p>Serch Teacher: <input type='search' name='q' placeholder='Search'></p>
  </form>
  <div class="row">
  {% for teacher in teachers_list %}
  <div class="col-6 col-md-4">
  <div class="student-box">
    <div class="imgBx">
      {% if teacher.teacher_profile_pic %}
      <img src="{{ teacher.teacher_profile_pic.url }}" alt="">
      {% else %}
      {% if forloop.counter0|divisibleby:"2" %}
      <img src="{% static 'images/login-avatar.PNG' %}" alt="">
      {% else %}
      <img src="{% static 'images/login-avatar-2.PNG' %}" alt="">
      {% endif %}
      {% endif %}
    </div>
    <div class="content">
      <h3>{{ teacher.name }}</h3>
      <p><i class="far fa-user"></i> Username: {{ teacher.user.username }}</p>
      <p><i class="fas fa-books"></i> Subject Name: {{ teacher.subject_name }}</p>
      <p><i class="far fa-phone"></i> Phone: {{ teacher.phone }}</p>
      <p><i class="far fa-envelope-open-text"></i> Email ID: {{ teacher.email }}</p>
      <a href="{% url 'classroom:write_message' pk=teacher.pk %}"><p class="add-button">Message</p> </a>
    </div>
  </div>
  </div>
  {% endfor %}
  </div>
</div>
</div>



<!--
  <div class="jumbotron">
    <h1>Given below is the list of all Teacher</h1>
    <h3>Click on "message" to message teacher</h3>

    <form method='GET' action="{% url 'classroom:teachers_list' %}">
      <input type='search' name='q' placeholder='Search'>
    </form>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Subject</th>
          <th scope="col"> </th>
        </tr>
      </thead>
      <tbody>
        {% for teacher in teachers_list %}
        <tr>
          <th>{{ teacher.name }}</th>
          <th>{{ teacher.subject_name }}</th>
          <th> <a class="btn btn-primary" href="{% url 'classroom:write_message' pk=teacher.pk %}">Message</a> </th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
-->
{% endblock %}

templates/update_marks.html
{% extends 'classroom/base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container">
<div class="jumbotron">
  {% if marks_updated %}
  <h2>Marks updated successfully.</h2>
  {% else %}
  <h1>Update Marks.</h1>
  <form  method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" value="Update">
  </form>
  {% endif %}
</div>
</div>
{% endblock %}